name : Joshua Montross
twitter : thecryocowboy
linkedin : joshuamontross
github : jmontross
email : joshua.montross@gmail.com
working_with_rails : 
personal_image : /images/FullSizeR.jpg
personal_site : http://www.pointmanj.com
job_title: Ruby / Rails Engineer
hire_availability : available
tagline: I get to the point. You can count on me in a pinch.