name : Daniel Guedea
twitter : danielguedea
linkedin : danielguedea
github : Daniel-Guedea
email : Daniel-Guedea@gmail.com
working_with_rails : 
personal_image : /images/daniel.jpg
personal_site : http://www.Daniel-Guedea.com
job_title: Veteran Software Engineer
hire_availability : available
tagline: I'm willing and able to learn anything I put my mind to.