name : Joshua Montross
twitter : jdmontross
linkedin : joshuamontross
github : jmontross
email : joshua.montross@gmail.com
working_with_rails : 
personal_image : /images/josh_up_redwoods.jpg
personal_site : http://www.joshuamontross.com
job_title: Ruby / Rails Engineer
hire_availability : unavailable
tagline: I get to the point. You can count on me in a pinch.