name : Joshua Montross
twitter : jdmontross
linkedin : joshuamontross
github : jmontross
email : joshua.montross@gmail.com
working_with_rails : jmontross
personal_image : /images/josh_up_redwoods.jpg
personal_site : http://www.joshuamontross.com
job_title: Ruby on Rails Developer
hire_availability : unavailable